// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoA3d1LEUJa9vrQpNGIeFZDrdQiJiq73s',
    appId: '1:167114516857:web:54b741736d151b9850a7a8',
    messagingSenderId: '167114516857',
    projectId: 'optizenqor-socity',
    authDomain: 'optizenqor-socity.firebaseapp.com',
    storageBucket: 'optizenqor-socity.firebasestorage.app',
    measurementId: 'G-RQM1G7G74Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzHINUxathu0AURt5nRYqyLhHqPHkRz7U',
    appId: '1:167114516857:android:b0c5fe92061deb2650a7a8',
    messagingSenderId: '167114516857',
    projectId: 'optizenqor-socity',
    storageBucket: 'optizenqor-socity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9R-lvW3h7HL8F5LtutIGcg3wF4zo6AnY',
    appId: '1:167114516857:ios:4885472abafea70950a7a8',
    messagingSenderId: '167114516857',
    projectId: 'optizenqor-socity',
    storageBucket: 'optizenqor-socity.firebasestorage.app',
    iosBundleId: 'com.example.optizenqorSocial',
  );
}
