class StorageKeys {
  StorageKeys._();

  static const authSession = 'auth_session';
  static const accessToken = 'access_token';
  static const refreshToken = 'refresh_token';
  static const currentUser = 'current_user';
  static const onboardingDone = 'onboarding_done';
  static const themeMode = 'theme_mode';
  static const localeCode = 'locale_code';
  static const searchHistory = 'search_history';
  static const draftPosts = 'draft_posts';
  static const cachedFeed = 'cached_feed';
  static const localCreatedPosts = 'local_created_posts';
  static const localStories = 'local_stories';
  static const seenStoryIds = 'seen_story_ids';
  static const cachedProfile = 'cached_profile';
  static const offlineQueue = 'offline_queue';
  static const feedScrollOffset = 'feed_scroll_offset';
  static const settingsState = 'settings_state';
  static const followState = 'follow_state';
  static const bookmarks = 'bookmarks';
  static const savedCollections = 'saved_collections';
  static const uploadTasks = 'upload_tasks';
  static const callHistory = 'call_history';
  static const groupChats = 'group_chats';
  static const activeAccountId = 'active_account_id';
  static const linkedAccounts = 'linked_accounts';
  static const verificationRequest = 'verification_request';
  static const blockedAccounts = 'blocked_accounts';
  static const mutedAccounts = 'muted_accounts';
  static const mutedGroups = 'muted_groups';
  static const activeSessions = 'active_sessions';
  static const loginHistory = 'login_history';
  static const recommendationPreferences = 'recommendation_preferences';
  static const notePreferences = 'note_preferences';
  static const postCreationSettings = 'post_creation_settings';
  static const chatPreferences = 'chat_preferences';
  static const dataExportRequests = 'data_export_requests';
  static const hiddenWords = 'hidden_words';
  static const contentSafetySettings = 'content_safety_settings';
  static const activeSubscriptionPlan = 'active_subscription_plan';
}
